=== OxfordSemantic/DataMapping/schema/mapping-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Tabular to RDF Data Mapping Schema",
  "type": "object",
  "required": ["schemaVersion", "mappingID", "tripleMaps"],
  "additionalProperties": false,
  "properties": {
    "schemaVersion": {
      "const": "0.2.0",
      "description": "This document must conform to schema version 0.2.0"
    },
    "mappingID": { "type": "string" },
    "mappingVersion": {
      "type": "string",
      "description": "Version of the document's content."
    },
    "mappingName": { "type": "string" },
    "prefixes": {
      "type": "object",
      "additionalProperties": { "type": "string" },
      "description": "Defines namespace prefixes for compact IRI usage."
    },
    "tripleMaps": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": ["subjectMap", "predicateObjectMaps"],
        "additionalProperties": false,
        "properties": {
          "subjectMap": {
            "type": "object",
            "required": ["value", "type"],
            "additionalProperties": false,
            "properties": {
              "value": { "type": "string" },
              "type": { "type": "string", "enum": ["IRI"] },
              "classes": {
                "type": "array",
                "items": { "type": "string" }
              }
            }
          },
          "predicateObjectMaps": {
            "type": "array",
            "items": {
              "type": "object",
              "required": ["predicate", "objectMap"],
              "additionalProperties": false,
              "properties": {
                "predicate": { "type": "string" },
                "objectMap": {
                  "type": "object",
                  "description": "Specifies how object values are constructed. If type=IRI, class can be used.",
                  "required": ["value", "type"],
                  "additionalProperties": false,
                  "properties": {
                    "value": { "type": "string" },
                    "type": { "type": "string" },
                    "lang": { "type": "string" },
                    "classes": {
                      "type": "array",
                      "items": { "type": "string" }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== OxfordSemantic/DataMapping/examples/people/mapping.json
{
  "schemaVersion": "0.2.0",
  "mappingVersion": "1.0.0",
  "mappingID": "uvw987",
  "mappingName": "Person",
  "prefixes": {
    "ex": "<http://example.com/>",
    "foaf": "<http://xmlns.com/foaf/0.1/>",
    "xsd": "<http://www.w3.org/2001/XMLSchema#>",
    "rdf": "<http://www.w3.org/1999/02/22-rdf-syntax-ns#>"
  },
  "tripleMaps": [
    {
      "subjectMap": {
        "value": "<http://example.com/person/{row#}>",
        "type": "IRI",
        "classes": [ "ex:Person" ]
      },
      "predicateObjectMaps": [
        {
          "predicate": "foaf:name",
          "objectMap": {
            "value": "{First Name} {Last Name}",
            "type": "xsd:string"
          }
        },
        {
          "predicate": "foaf:name",
          "objectMap": {
            "value": "{First Name} {Last Name}",
            "type": "rdf:langString",
            "lang": "pl"
          }
        },
        {
          "predicate": "ex:sex",
          "objectMap": {
            "value": "{Sex}",
            "type": "xsd:string"
          }
        },
        {
          "predicate": "ex:age",
          "objectMap": {
            "value": "{Age}",
            "type": "xsd:integer"
          }
        }
      ]
    }
  ]
}

=== OxfordSemantic/DataMapping/examples/flight/mapping.json
{
  "schemaVersion": "0.2.0",
  "mappingVersion": "1.0.0",
  "mappingID": "55662e93fc674408a9b4f466a6aa815f",
  "mappingName": "Flights",
  "prefixes": {
    "fl": "<http://www.flights.com/>",
    "foaf": "<http://xmlns.com/foaf/0.1/>",
    "xsd": "<http://www.w3.org/2001/XMLSchema#>"
  },
  "tripleMaps": [
    {
      "subjectMap": {
        "value": "fl:{row#}",
        "type": "IRI",
        "classes": [ "fl:Flight" ]
      },
      "predicateObjectMaps": [
        {
          "predicate": "fl:date",
          "objectMap": {
            "value": "{FL_DATE}",
            "type": "xsd:string"
          }
        },
        {
          "predicate": "fl:departureDelayInMinutes",
          "objectMap": {
            "value": "{DEP_DELAY}",
            "type": "xsd:decimal"
          }
        }
      ]
    },
    {
      "subjectMap": {
        "value": "<http://www.flights.com/{row#}>",
        "type": "IRI",
        "classes": [ "fl:Flight" ]
      },
      "predicateObjectMaps": [
        {
          "predicate": "fl:arrivalDelayInMinutes",
          "objectMap": {
            "value": "{ARR_DELAY}",
            "type": "xsd:decimal"
          }
        },
        {
          "predicate": "fl:flightDuration",
          "objectMap": {
            "value": "P{AIR_TIME}M",
            "type": "xsd:duration"
          }
        },
        {
          "predicate": "fl:distance",
          "objectMap": {
            "value": "{DISTANCE}",
            "type": "xsd:decimal"
          }
        }
      ]
    }
  ]
}

=== OxfordSemantic/DataMapping/examples/hr/employees-mapping.json
{
  "schemaVersion": "0.2.0",
  "mappingVersion": "1.0.0",
  "mappingID": "some-unique-id-12345",
  "mappingName": "Employees",
  "prefixes": {
    "": "<http://example.com/hr/vocabulary#>",
    "departments": "<http://example.com/hr/departments/>",
    "employees": "<http://example.com/hr/employees/>",
    "foaf": "<http://xmlns.com/foaf/0.1/>",
    "xsd": "<http://www.w3.org/2001/XMLSchema#>"
  },
  "tripleMaps": [
    {
      "subjectMap": {
        "value": "employees:{EmployeeID}",
        "type": "IRI",
        "classes": [ ":Employee", "foaf:Person" ]
      },
      "predicateObjectMaps": [
        {
          "predicate": "foaf:name",
          "objectMap": {
            "value": "{Name}",
            "type": "xsd:string"
          }
        },
        {
          "predicate": ":department",
          "objectMap": {
            "value": "departments:{DepartmentID}",
            "type": "IRI",
            "classes": [ ":Department" ]
          }
        }
      ]
    }
  ]
}

=== OxfordSemantic/DataMapping/examples/employment/mapping.json
{
  "schemaVersion": "0.2.0",
  "mappingVersion": "1.0.0",
  "mappingID": "abc123",
  "mappingName": "Person",
  "prefixes": {
    "ex": "<http://example.com/>",
    "foaf": "<http://xmlns.com/foaf/0.1/>",
    "xsd": "<http://www.w3.org/2001/XMLSchema#>",
    "company": "<http://example.com/company/>",
    "rdf": "<http://www.w3.org/1999/02/22-rdf-syntax-ns#>"
  },
  "tripleMaps": [
    {
      "subjectMap": {
        "value": "<http://example.com/person/{ID}>",
        "type": "IRI",
        "classes": [ "ex:Person", "<http://example.com/class with spaces>" ]
      },
      "predicateObjectMaps": [
        {
          "predicate": "foaf:name",
          "objectMap": {
            "value": "{FirstName} {LastName}",
            "type": "xsd:string"
          }
        },
        {
          "predicate": "foaf:name",
          "objectMap": {
            "value": "{FirstName} {LastName}",
            "type": "rdf:langString",
            "lang": "pl"
          }
        },
        {
          "predicate": "ex:worksFor",
          "objectMap": {
            "value": "company:{CompanyID}",
            "type": "IRI",
            "classes": [ "ex:Company" ]
          }
        },
        {
          "predicate": "ex:employedOn",
          "objectMap": {
            "value": "{Year}-01-01",
            "type": "xsd:date"
          }
        }
      ]
    },
    {
      "subjectMap": {
        "value": "company:{CompanyID}",
        "type": "IRI",
        "classes": [ "ex:Company" ]
      },
      "predicateObjectMaps": [
        {
          "predicate": "foaf:name",
          "objectMap": {
            "value": "{CompanyName}",
            "type": "xsd:string"
          }
        }
      ]
    }
  ]
}

=== OxfordSemantic/DataMapping/examples/northwind/orderDetails.json
{
  "schemaVersion": "0.2.0",
  "mappingID": "e25pzq8ZWseCc5mqsrh4bS",
  "mappingName": "Order Details",
  "prefixes": {
    "": "<http://www.example.com/terms/>",
    "xsd": "<http://www.w3.org/2001/XMLSchema#>",
    "product": "<http://www.example.com/terms/Product/>",
    "orderDetail": "<http://www.example.com/terms/OrderDetail/>",
    "order": "<http://www.example.com/terms/Order/>"
  },
  "tripleMaps": [
    {
      "subjectMap": {
        "value": "orderDetail:{ID}",
        "type": "IRI",
        "classes": [
          ":OrderDetail"
        ]
      },
      "predicateObjectMaps": [
        {
          "predicate": ":unitPrice",
          "objectMap": {
            "value": "{unitPrice}",
            "type": "xsd:decimal"
          }
        },
        {
          "predicate": ":discount",
          "objectMap": {
            "value": "{discount}",
            "type": "xsd:decimal"
          }
        },
        {
          "predicate": ":quantity",
          "objectMap": {
            "value": "{quantity}",
            "type": "xsd:integer"
          }
        },
        {
          "predicate": ":hasProduct",
          "objectMap": {
            "value": "product:{productID}",
            "type": "IRI",
            "classes": [
              ":Product"
            ]
          }
        },
        {
          "predicate": ":referencedInRow",
          "objectMap": {
            "value": "{row#}",
            "type": "xsd:integer"
          }
        }
      ]
    },
    {
      "subjectMap": {
        "value": "product:{productID}",
        "type": "IRI",
        "classes": [
          ":Product"
        ]
      },
      "predicateObjectMaps": []
    },
    {
      "subjectMap": {
        "value": "order:{orderID}",
        "type": "IRI",
        "classes": [
          ":Order"
        ]
      },
      "predicateObjectMaps": [
        {
          "predicate": ":hasOrderDetail",
          "objectMap": {
            "value": "orderDetail:{ID}",
            "type": "IRI",
            "classes": [
              ":OrderDetail"
            ]
          }
        }
      ]
    }
  ]
}

=== OxfordSemantic/DataMapping/examples/transactions/mapping.json
{
  "schemaVersion": "0.2.0",
  "mappingVersion": "1.0.0",
  "mappingID": "some-unique-id-12345",
  "mappingName": "Transactions",
  "prefixes": {
    "": "<http://example.com/transactions/vocabulary#>",
    "accounts": "<http://example.com/transactions/accounts/>",
    "clients": "<http://example.com/transactions/clients/>",
    "transactions": "<http://example.com/transactions/transactions/>",
    "xsd": "<http://www.w3.org/2001/XMLSchema#>"
  },
  "tripleMaps": [
    {
      "subjectMap": {
        "value": "clients:{ClientID}",
        "type": "IRI",
        "classes": [ ":Client" ]
      },
      "predicateObjectMaps": [
        {
          "predicate": ":hasBankAccount",
          "objectMap": {
            "value": "accounts:{DestinationAccount}",
            "type": "IRI",
            "classes": [ ":BankAccount" ]
          }
        }
      ]
    },
    {
      "subjectMap": {
        "value": "accounts:{DestinationAccount}",
        "type": "IRI",
        "classes": [ ":BankAccount" ]
      },
      "predicateObjectMaps": [
        {
          "predicate": ":hasAccountNumber",
          "objectMap": {
            "value": "{DestinationAccount}",
            "type": "xsd:string"
          }
        },
        {
          "predicate": ":hasTransaction",
          "objectMap": {
            "value": "transactions:{TransactionID}",
            "type": "IRI",
            "classes": [ ":Transaction" ]
          }
        }
      ]
    },
    {
      "subjectMap": {
        "value": "transactions:{TransactionID}",
        "type": "IRI",
        "classes": [ ":Transaction" ]
      },
      "predicateObjectMaps": [
        {
          "predicate": ":hasReference",
          "objectMap": {
            "value": "{Reference}",
            "type": "xsd:string"
          }
        },
        {
          "predicate": ":hasValue",
          "objectMap": {
            "value": "{Value}",
            "type": "xsd:string"
          }
        },
        {
          "predicate": ":onDate",
          "objectMap": {
            "value": "{Year}-{Month}-{Day}",
            "type": "xsd:string"
          }
        },
        {
          "predicate": ":hasSourceBankAccount",
          "objectMap": {
            "value": "accounts:{SourceAccount}",
            "type": "IRI",
            "classes": [ ":BankAccount" ]
          }
        }
      ]
    }
  ]
}

=== OxfordSemantic/DataMapping/examples/hr/departments-mapping.json
{
  "schemaVersion": "0.2.0",
  "mappingVersion": "1.0.0",
  "mappingID": "some-unique-id-12345",
  "mappingName": "Departments",
  "prefixes": {
    "": "<http://example.com/hr/vocabulary#>",
    "departments": "<http://example.com/hr/departments/>",
    "employees": "<http://example.com/hr/employees/>",
    "foaf": "<http://xmlns.com/foaf/0.1/>",
    "xsd": "<http://www.w3.org/2001/XMLSchema#>"
  },
  "tripleMaps": [
    {
      "subjectMap": {
        "value": "departments:{Department ID}",
        "type": "IRI",
        "classes": [ ":Department" ]
      },
      "predicateObjectMaps": [
        {
          "predicate": "foaf:name",
          "objectMap": {
            "value": "{Department Name}",
            "type": "xsd:string"
          }
        }
      ]
    }
  ]
}

=== OxfordSemantic/DataMapping/examples/titanic/mapping.json
{
  "schemaVersion": "0.2.0",
  "mappingVersion": "3.8.2",
  "mappingID": "2G61MDQAXvkwYbtm5FMUhG",
  "mappingName": "Titanic Passenger Mapping",
  "prefixes": {
    "": "<http://example.com/titantic/vocabulary#>",
    "passengers": "<http://example.com/titantic/passengers/>",
    "classes": "<http://example.com/titantic/passenger-classes/>",
    "foaf": "<http://xmlns.com/foaf/0.1/>",
    "xsd": "<http://www.w3.org/2001/XMLSchema#>"

  },
  "tripleMaps": [
    {
      "subjectMap": {
        "value": "passengers:{PassengerId}",
        "type": "IRI",
        "classes": [ ":Passenger" ]
      },
      "predicateObjectMaps": [
        {
          "predicate": "foaf:name",
          "objectMap": {
            "value": "{Name}",
            "type": "xsd:string"
          }
        },
        {
          "predicate": ":sex",
          "objectMap": {
            "value": "{Sex}",
            "type": "xsd:string"
          }
        },
        {
          "predicate": "foaf:age",
          "objectMap": {
            "value": "{Age}",
            "type": "xsd:decimal"
          }
        },
        {
          "predicate": ":passengerClass",
          "objectMap": {
            "value": "classes:{Pclass}",
            "type": "IRI",
            "classes": [ ":PassengerClass" ]
          }
        },
        {
          "predicate": ":referencedInRow",
          "objectMap": {
            "value": "{row#}",
            "type": "xsd:int"
          }
        }
      ]
    }
  ]
}
